import { useState } from "react";
import ApplicationForm from "./components/ApplicationForm";
import AdminLogin from "./components/AdminLogin";
import AdminDashboard from "./components/AdminDashboard";
import CareerFitAssistant from "./components/CareerFitAssistant";

const data=[[["طالب سنة أخيرة","Final-year student",2],["خريج جديد","Recent graduate",3],["أغيّر مجالي","Changing fields",2]],[["نعم، نسخة أولية","Yes, an initial version",3],["نعم، لكنه قديم","Yes, but it is old",2],["لا يوجد بعد","Not yet",1]],[["نعم بوضوح","Yes, clearly",3],["إلى حد ما","To some extent",2],["ما زلت أبحث","Still exploring",1]],[["جيدة","Comfortable",3],["أساسية إلى متوسطة","Basic to intermediate",2],["ضعيفة جدًا","Very limited",1]],[["نعم","Yes",3],["قد أحتاج تجهيزًا بسيطًا","With preparation",2],["ليس حاليًا","Not currently",1]]];
const questions=[["ما المرحلة المهنية التي تمر بها؟","What career stage are you in?"],["هل لديك CV حالي؟","Do you have a current CV?"],["هل تعرف المجالات التي تستهدفها؟","Do you know your target fields?"],["كيف تصف قدرتك على قراءة إعلان وظيفة بالإنجليزية؟","How comfortable are you reading job descriptions in English?"],["هل تستطيع إحضار لابتوب؟","Can you bring a laptop?"]];
const info={ready:[["جاهز للتقديم","لديك أساس مناسب للاستفادة من المختبر.",["حدّد وظيفة مستهدفة.","حضّر CV أولياً.","انتقل إلى طلب المشاركة."]],["Ready to apply","You have a solid foundation for the workshop.",["Choose a target role.","Prepare an initial CV.","Continue to your application."]]],preparing:[["جاهز مع بعض التحسينات","أنت قريب، لكن تحتاج ترتيب بعض الأساسيات.",["حدّث CV.","وضّح المجال المستهدف.","راجع إعلان وظيفة بالإنجليزية."]],["Ready with a few improvements","You are close, with a few basics to organize.",["Update your CV.","Clarify your target field.","Review an English job post."]]],starter:[["تحتاج تجهيزًا أوليًا","ابدأ بالأساسيات ثم انضم عندما تكون جاهزًا.",["أنشئ CV أوليًا.","اختر مجالاً تستكشفه.","تدرّب على إعلانات الوظائف."]],["A little preparation first","Start with the basics before joining.",["Create an initial CV.","Choose a field to explore.","Practice job descriptions."]]]};
export default function App(){const [lang,setLang]=useState(()=>localStorage.getItem("careerfit-language")||"ar"),[answers,setAnswers]=useState([]),[at,setAt]=useState(null),[adminUser,setAdminUser]=useState(null),[assistantOpen,setAssistantOpen]=useState(()=>{const shouldRestore=window.sessionStorage.getItem("careerfit-assistant-restore-open")==="true";window.sessionStorage.removeItem("careerfit-assistant-restore-open");return shouldRestore});const isAdminRoute=window.location.pathname.replace(/\/+$/,"")==="/admin";
    if(isAdminRoute)return adminUser?<AdminDashboard adminUser={adminUser}/>:<AdminLogin onAuthenticated={setAdminUser}/>;const ar=lang==="ar",done=answers.length===5,score=answers.reduce((a,b)=>a+b,0),tier=score>=13?"ready":score>=9?"preparing":"starter",r=info[tier][ar?0:1];return <div className="app-shell" dir={ar?"rtl":"ltr"}><header className="site-header"><a className="brand" href="#hero"><b>CL</b><span>CareerFit Lab</span></a><div><button type="button" className="lang" onClick={()=>{if(assistantOpen){window.sessionStorage.setItem("careerfit-assistant-restore-open","true");window.setTimeout(()=>window.sessionStorage.removeItem("careerfit-assistant-restore-open"),0)}const n=ar?"en":"ar";setLang(n);localStorage.setItem("careerfit-language",n)}}>{ar?"EN":"العربية"}</button></div></header><main><section id="hero" className="hero"><div><span className="eyebrow">{ar?"مختبر عملي للتقديم الذكي للوظائف":"Practical job-application workshop"}</span><h1>{ar?"قدّم لفرصك بثقة، وبطريقة تناسبك فعلًا.":"Apply with confidence and genuine direction."}</h1></div></section><section id="fit" className="section tint"><div className="section-heading"><span>{ar?"هل يناسبك؟":"Readiness"}</span><h2>{ar?"اختبار جاهزية سريع":"Quick readiness check"}</h2></div><div className="quiz">{!done?<><div className="progress"><span>{answers.length+1}/5</span><i><em style={{width:`${answers.length*20}%`}}/></i></div><h3>{questions[answers.length][ar?0:1]}</h3><div className="answers">{data[answers.length].map(([a,b,v])=><button key={a} onClick={()=>{const n=[...answers,v];setAnswers(n);if(n.length===5)setAt(new Date().toISOString())}}>{ar?a:b}<b>+</b></button>)}</div></>:<div className="quiz-result"><span>{r[0]} · {score}/15</span><h3>{r[1]}</h3><ul className="list">{r[2].map(x=><li key={x}>{x}</li>)}</ul><div className="actions"><a className="button primary" href="#register">{ar?"تابع إلى الطلب":"Continue to application"}</a><button className="button secondary" onClick={()=>{setAnswers([]);setAt(null)}}>{ar?"أعد الاختبار":"Retake"}</button></div></div>}</div></section><section id="register" className="section form-section"><ApplicationForm language={lang} quiz={done?{quizCompleted:true,quizAnswers:answers,quizScore:score,quizResultTier:tier,quizCompletedAt:at}:null}/></section><section className="section site-contact" aria-label={ar?"التواصل":"Contact"}><div className="site-contact__inner"><div className="site-contact__copy"><h2>{ar?"لديك سؤال قبل التقديم؟":"Have a question before applying?"}</h2><p>{ar?"يمكنك التواصل مباشرة مع كريم للاستفسارات المتعلقة بـ CareerFit Lab.":"You can contact Karim directly with questions about CareerFit Lab."}</p></div><div className="site-contact__actions"><a href="mailto:karim.s.a.jaber@gmail.com">{ar?"البريد الإلكتروني":"Email"}</a><a href="https://wa.me/970598396658" target="_blank" rel="noreferrer">WhatsApp</a></div></div></section></main><CareerFitAssistant language={lang} isOpen={assistantOpen} onOpenChange={setAssistantOpen}/></div>}
